name: Generate Markdown

on:
  workflow_dispatch:
    inputs:
      output_path:
        description: "Output file path relative to the repository (e.g., /README.md)"
        required: true
        default: "README.md"
      template_path:
        description: "Path to the template file relative to the repository"
        required: true
        default: ".generate_md/templates/README.md"

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Generate Markdown
        id: generate_markdown
        run: |
          python .generate_md/script/generate_markdown.py --template "${{ github.event.inputs.template_path }}" --output "${{ github.event.inputs.output_path }}"

      - name: Check for changes
        id: check_changes
        run: |
          git add "${{ github.event.inputs.output_path }}"
          git diff --cached --quiet || echo "Changes detected"

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Automated update: Generated markdown file"
          git push
